Module ModelParam_Inputs

  use ModelParamToolbox
  use ModelDimensions

  implicit none


      real*4 QFW    (dimMS)    !  Scale factor for water
      real*4 QFP    (dimMS)    !  Scale factor of P  discharge
      real*4 QFN    (dimMS)    !  Scale factor of N  discharge
      real*4 QFC    (dimMS)    !  Scale factor of C  discharge
      real*4 QFODM  (dimMS)    !  Scale factor of OD discharge
      real*4 QFS    (dimMS)    !  Scale factor of Silicate discharge

           ! QFODM and QFS combined with QFW (spec. as conc.

      real*4 QFNH4  (dimMS)    !  Limit on fraction of N as ammonium

  ! ################################################################
  !  Transfer of sources in RUNOFF to other outlets
  !  than specified in RUNOFF:

                   ! Fractions [0..1] to transfer to other
                   ! (after scaling, both water and nutrients):
      real*4    QTRF   (dimMS,dimMS)

                   !  Outlets to transfer to:
      INTEGER QTRNDX (dimMS,dimMS)
                   ! Usage: fill from left in first index
                   ! for each primary outlet (second index)
                   ! terminate by 0.

                   ! Time in year (day nr.) for
                   ! turning transfer on (k,1) or off (k,2)
      real*4     QTR_Times(dimMS,2)

  ! ################################################################
  ! Variation factors of primary sources:
 
  ! Outlet arrangements:

      INTEGER  BASINQ(dimMS)     ! Number of receiving basin

      real*4     QDIAM (dimMS)
               ! Diameter of discharge if dived outlet
               ! or vertical extension if surface outlet

      INTEGER  NHOLES(dimMS)  ! Number of holes in outlet

      real*4    DEPTHQ(dimMS,2)
                ! (k,1): Outlet depths
                ! (k,2): Intake depths for recipient water
                !        taken into the outlet


      ! ---------------------------------------------------
      real*4     QMIXIN(dimMS)   ! Recipient water to mix in (m3/s)


      real*4     MIXQTM (dimMS,2)
               ! Time in year (day nr.) for
               ! turning mixing on (k,1) or off (k,2)


      ! ==============================================================
      ! Option for controlling transfers and recipient water mix-in
      ! to outlet by bottom oxygen concentration in receiving basin:

      real*4 QTR_OXCOND(dimMS,2)
          ! If oxygen conc. in bottom water of receiving basin
          ! drops below QTR_OXCOND(dimMS,1), the transfer
          ! is activated for one month, or until the oxygen
          ! concentration reaches QTR_OXCOND(dimMS,2)
          ! within seasonal constraints above

      real*4 QTR_CheckInterval     ! Time interval for checking
                                 ! oxygen conditions

      real*4 QTR_MinActiveInterval ! minimum active period (days)
                                 ! when turned on. 

      real*4 RANDFACTOR(dimMS)
           !  Strength of random variations in input
           !  <=0: no variations
           !  >0:  EXP(x) = factor of relative variation
           !  Frequency defined in RUNOFF.FOR


       real*4 AIRTQF(dimMS)
            ! Degree of influence from air temperature on water

       real*4 QCDETF(dimMS)
            ! Fraction of carbon entering detritus and sinking

       real*4 QNDETF(dimMS)
       real*4 QPDETF(dimMS)
            !  Upper limits to fraction of N and P entering
            !  detritus (the rest to NO3, NH4, PO4)

       real*4 QNCDET, QPCDET
            ! Upper limit to C:N and C:P ratio in particulate
            ! matter generated by river input and sewage input

       real*4 DTJETM
      !  time interval for recalculating transports due to
      !  dived jets in TRANSP.  Saves time

       real*4 RNF
          ! Common factor for all land runoffs, controls
          ! input of substances and heat content in QCALC,
          ! does not affect water volumes


        ! ********* Inorganic particles: ******************
        ! particle influx rates as g/s, combines with volume flux m3/s
        ! to concentration g/s or mg/l
    real*4 QFSPP(dimMS)
    real*4 TIME_SPP(2)! time on/off in days
        ! Net effect of particles on density;
    real*4 dDens_dSPP
        ! Assuming wet sediment has density = 1.5*density of water
        ! and water content 50% by weight.
    real*4 SPP_SINK_VELOCITY
         ! sinking velocity of particles, in unit m/day


   Contains


!=================================================================

      Subroutine ParamGroup_Inputs


      call paramGroup("Inputs to model by runoff from land","INPUTS")

            call ParamExpl("Adjustment factors for runoff:")

      call ParamDeclRealArray(QFW,(/1.0/),"QFW","",&
                "Scale factor for water")

      call ParamDeclRealArray(QFP,(/1.0/),"QFP","",&
                "Scale factor of P  discharge")

      call ParamDeclRealArray(QFN,(/1.0/),"QFN","",&
                "Scale factor of N  discharge")

      call ParamDeclRealArray(QFC,(/1.0/),"QFC","",&
                "Scale factor of C  discharge")

      call ParamDeclRealArray(QFODM,(/1.0/),"QFODM","",&
                "Scale factor of oxygen demand (OD) discharge")

      call ParamDeclRealArray(QFS,(/1.0/),"QFS","",&
                "Scale factor of Silicate discharge")

            call ParamExpl("QFODM and QFS combined with QFW")

      call ParamDeclRealArray(QFNH4,(/1.0/),"QFNH4","",&
                "Limit on fraction of N as ammonium"//&
                " relative to spec. in code in Runoff.FOR")

  ! ################################################################
  !  Transfer of sources in RUNOFF to other outlets
  !  than specified in RUNOFF:

      call ParamDeclRealMatrix( QTRF, reshape((/0.0,0.0/),(/1,1/)),"QTRF","",&
                "Fractions [0..1] to transfer from sources to other outlets"//&
                "  (after source adjustments," //&
                "   applies to both water and nutrients)")


      call ParamDeclIntegerMatrix(QTRNDX,reshape((/0,0/),(/1,1/)),"QTRNDX","",&
                "Which Outlets to transfer to:" //&
                " Usage: fill from left in first index" //&
                " for each primary outlet (second index)" //&
                " terminate by 0.")

      call ParamDeclRealMatrix(QTR_Times,reshape((/0.0,365.0/),(/1,2/)),"QTR_Times","",&
                " Time in year (day nr.) for"//&
                " turning transfer on (k,1) or off (k,2)")


            call ParamExpl("Variation factors for outlet arrangements:")


      call ParamDeclIntegerArray(BASINQ, (/4,1,6,2,7,8,3,5,5,3,2,1,1,3,6/),"BASINQ","",&
                "Number of the receiving basin for each outlet"//&
                " Initially all outlets to basin 1:"//&
                " should be reset by command-file input")

      call ParamDeclRealArray( QDIAM,(/1.0/),"QDIAM","",&
                "Diameter of discharge for dived pipeline outlet"//&
                " or vertical extension if surface outlet")

      call ParamDeclIntegerArray(NHOLES, (/1/),"NHOLES","",&
                "Number of holes in each dived outlet")

      call ParamDeclRealMatrix(DEPTHQ, reshape((/0.0,0.0/),(/1,1/)),"DEPTHQ","",&
                " (k,1): Outlet depths" // &
                " (k,2): Intake depths for recipient water" // &
                "        taken into the outlet")

      call ParamDeclRealArray(QMIXIN ,(/0.0/),"QMIXIN","",&
                "Recipient water to mix into outlet (m3/s)")


      call ParamDeclRealMatrix( MIXQTM,reshape((/0.0, 365.0/),(/1,1/)),"MIXQTM","",&
                "Time in year (day number [0...365]" // &
                " for turning mixing on (k,1) or off (k,2)")


            call ParamExpl("Option for controlling source transfers" // &
                           " and recipient water mix-in to outlet" // &
                           " by bottom oxygen concentration in receiving basin:")


      call ParamDeclRealMatrix( QTR_OXCOND, reshape((/20.0, 20.0/),(/1,1/)),"QTR_OXCOND","",&
                " If oxygen conc. in bottom water of receiving basin" // &
                " drops below QTR_OXCOND(dimMS,1), the transfer" // &
                "  is activated for one month, or until the oxygen" // &
                "  concentration reaches QTR_OXCOND(dimMS,2)" // &
                "  within seasonal constraints above")

      call ParamDeclReal( QTR_CheckInterval,7.0,"QTR_CheckInterval","",&
                "Time interval for checking oxygen conditions")
                
      call ParamDeclReal( QTR_MinActiveInterval, 30.0,"QTR_MinActiveInterval","",&
                "Minimum active period (days)"// &
                "when Transfers and mixing is turned on.")
      
      call ParamDeclRealArray(RANDFACTOR,(/0.0/),"RANDFACTOR","",&
               "Strength of random variations in input"// &
               "  <=0: no variations"// &
               "  >0 : EXP(x) = factor of relative variation"// &
               " Frequency defined in RUNOFF.FOR")

      call ParamDeclRealArray(AIRTQF,(/0.0/),"AIRTQF","",&
                " Degree of influence from air temperature on water")

      call ParamDeclRealArray(QCDETF,(/0.01/),"QCDETF","",&
                " Fraction of carbon entering detritus and sinking")

      call ParamDeclRealArray(QNDETF,(/1.0/),"QNDETF","",&
                "Upper limits to fraction of N entering"// &
                " detritus (the rest to NO3, NH4)")
      
      call ParamDeclRealArray(QPDETF,(/1.0/),"QPDETF","",&
                "Upper limits to fraction of P entering"// &
                " detritus (the rest to PO4)")

      call ParamDeclReal( QNCDET, 0.1,"QNCDET","",&
                "Upper limit to C:N ratio"// &
                " in particulate matter from inputs")

      call ParamDeclReal( QPCDET, 0.01, "QPCDET","",&
                "Upper limit to C:P ratio"// &
                " in particulate matter from inputs")

      call ParamDeclReal( DTJETM ,0.5, "DTJETM","",&
                "Time interval for recalculating transports due to"// &
                " dived jets in TRANSP.  Saves time")

      call ParamDeclReal( RNF, 1.0, "RNF","",&
                "Common factor for all land runoffs, controls"// &
                " input of substances and heat content in QCALC,"// &
                " does not affect water volumes")


        ! ********* Inorganic particles: ******************

      call ParamDeclRealArray(QFSPP,(/0.0/),"QFSPP","(g/s)",&
                "Particle influx rates, combines with" // &
                " volume flux m3/s to concentration g/m3 or mg/l")

      call ParamDeclRealArray(TIME_SPP,(/0.0/),"TIME_SPP","",&
                " time on/off in days")

            call ParamExpl("Net effect of particles on density:")

      call ParamDeclReal( dDens_dSPP, 0.333333,"dDens_dSPP","",&
                "Assuming wet sediment has density = 1.5*density of water"// &
                " and water content 50% by weight.")


      call ParamDeclReal( SPP_SINK_VELOCITY, 0.0,"SPP_SINK_VELOCITY","",&
                "sinking velocity of particles, in unit m/day")

      end subroutine ParamGroup_Inputs


end Module
